/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.locadoraauto.view;
import com.mycompany.locadoraauto.interfaces.Interface;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vitor
 */
public class FMenu extends javax.swing.JFrame {

    private JCadastro dcad;
    private DLogin dlog;
    private jLocacao jloc;
    private Interface Locadora;
    
    public FMenu(Interface Locadora) {
        this.Locadora = Locadora;
        boolean menu = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jLogin = new javax.swing.JMenu();
        jLoginButton = new javax.swing.JMenuItem();
        jCadastrar = new javax.swing.JMenu();
        jCadastro = new javax.swing.JMenuItem();
        jAlterar = new javax.swing.JMenuItem();
        jLocadora = new javax.swing.JMenu();
        jAlugar = new javax.swing.JMenuItem();
        jCompraVenda = new javax.swing.JMenu();
        jVenda = new javax.swing.JMenuItem();
        jRegistro = new javax.swing.JMenu();
        jLista = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jLogin.setText("Login");

        jLoginButton.setText("Logar");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });
        jLogin.add(jLoginButton);

        jMenuBar1.add(jLogin);

        jCadastrar.setText("Controle");

        jCadastro.setText("Cadastro");
        jCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroActionPerformed(evt);
            }
        });
        jCadastrar.add(jCadastro);

        jAlterar.setText("Alterar");
        jCadastrar.add(jAlterar);

        jMenuBar1.add(jCadastrar);

        jLocadora.setText("Locadora");

        jAlugar.setText("Alugar");
        jAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlugarActionPerformed(evt);
            }
        });
        jLocadora.add(jAlugar);

        jMenuBar1.add(jLocadora);

        jCompraVenda.setText("Compra/Venda");

        jVenda.setText("Venda");
        jCompraVenda.add(jVenda);

        jMenuBar1.add(jCompraVenda);

        jRegistro.setText("Registro");

        jLista.setText("Lista");
        jRegistro.add(jLista);

        jMenuBar1.add(jRegistro);

        jMenu1.setText("Sair");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroActionPerformed
        // TODO add your handling code here:
        dcad = new JCadastro(this, true, Locadora);
        dcad.setVisible(true);
    }//GEN-LAST:event_jCadastroActionPerformed

    private void jAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlugarActionPerformed
        try {
            jloc = new jLocacao(this, true, Locadora);
        } catch (RemoteException | SQLException ex) {
            Logger.getLogger(FMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        jloc.setVisible(true);
    }//GEN-LAST:event_jAlugarActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        dlog = new DLogin(this, true);
        dlog.setVisible(true);
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAlterar;
    private javax.swing.JMenuItem jAlugar;
    private javax.swing.JMenu jCadastrar;
    private javax.swing.JMenuItem jCadastro;
    private javax.swing.JMenu jCompraVenda;
    private javax.swing.JMenuItem jLista;
    private javax.swing.JMenu jLocadora;
    private javax.swing.JMenu jLogin;
    private javax.swing.JMenuItem jLoginButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jRegistro;
    private javax.swing.JMenuItem jVenda;
    // End of variables declaration//GEN-END:variables
}
