/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.locadoraauto.view;

import javax.swing.JOptionPane;
import com.mycompany.locadoraauto.interfaces.Interface;
import com.mycompany.locadoraauto.models.Automovel;
import com.mycompany.locadoraauto.models.Alugador;
import com.mycompany.locadoraauto.models.Locador;
import com.mycompany.locadoraauto.models.Seguro;
import com.mycompany.locadoraauto.models.Usuario;
import java.awt.Component;
import java.rmi.AccessException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitor
 */
public class JDialogLocacao extends javax.swing.JDialog {

    private Interface Locadora;
    ArrayList<Automovel> automoveis;
    DefaultTableModel modelL;
    Alugador userC;
    Locador userL;

    /**
     * Creates new form jLocacao
     */
    public JDialogLocacao(java.awt.Frame parent, boolean modal, Interface Locadora, ArrayList<Automovel> automoveis) throws RemoteException, SQLException {
        super(parent, modal);
        this.Locadora = Locadora;
        this.automoveis = automoveis;
        userC = null;
        userL = null;
        initComponents();
        modelL = new DefaultTableModel(new String[]{"ID", "Modelo", "Tipo", "Valor Diaria", "Status"}, 0);
        try {
            Registry r = LocateRegistry.getRegistry("26.210.206.180", 1099);
            this.Locadora = (Interface) r.lookup("Ola");
            System.out.println("OLA");
        } catch (NotBoundException | AccessException ex) {
            Logger.getLogger(JDialogCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(modelL);
        jScrollPane1.setViewportView(jTable1);

        jTable1.revalidate();
        jTable1.repaint();
        jConfirmAluga.setEnabled(false);
        jToggleFound.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanelVazio = new javax.swing.JPanel();
        jDevolucao = new javax.swing.JPanel();
        jIDContrato = new javax.swing.JTextField();
        jIDCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jAlugar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jConfirmAluga = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextBusca = new javax.swing.JTextField();
        jToggleFound = new javax.swing.JToggleButton();
        jButtonBuscar = new javax.swing.JButton();
        jComboSeguro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelVazioLayout = new javax.swing.GroupLayout(jPanelVazio);
        jPanelVazio.setLayout(jPanelVazioLayout);
        jPanelVazioLayout.setHorizontalGroup(
            jPanelVazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        jPanelVazioLayout.setVerticalGroup(
            jPanelVazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelVazio, "card4");

        jIDContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDContratoActionPerformed(evt);
            }
        });

        jLabel1.setText("Informe o ID do contrato");

        jLabel2.setText("Informe a identificação do cliente");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDevolucaoLayout = new javax.swing.GroupLayout(jDevolucao);
        jDevolucao.setLayout(jDevolucaoLayout);
        jDevolucaoLayout.setHorizontalGroup(
            jDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDevolucaoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jIDCliente)
                    .addComponent(jIDContrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jDevolucaoLayout.setVerticalGroup(
            jDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDevolucaoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIDContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        jPanel1.add(jDevolucao, "card3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Modelo", "Tipo", "Valor Diaria", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setRowHeight(40);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Selecione o automóvel a ser alugado");

        jConfirmAluga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jConfirmAluga.setText("Alugar");
        jConfirmAluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmAlugaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome Cliente");

        jToggleFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleFoundActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jComboSeguro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avancado", "Intermediario", "Basico" }));

        jLabel6.setText("Seguro");

        javax.swing.GroupLayout jAlugarLayout = new javax.swing.GroupLayout(jAlugar);
        jAlugar.setLayout(jAlugarLayout);
        jAlugarLayout.setHorizontalGroup(
            jAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
            .addGroup(jAlugarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAlugarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jConfirmAluga, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jAlugarLayout.createSequentialGroup()
                        .addGroup(jAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jAlugarLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(251, 251, 251)
                                .addGroup(jAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(288, Short.MAX_VALUE))
                    .addGroup(jAlugarLayout.createSequentialGroup()
                        .addGroup(jAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jAlugarLayout.createSequentialGroup()
                                .addComponent(jTextBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleFound, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonBuscar))
                        .addGap(0, 446, Short.MAX_VALUE))))
        );
        jAlugarLayout.setVerticalGroup(
            jAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAlugarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jConfirmAluga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAlugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleFound, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addComponent(jComboSeguro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jAlugar, "card2");

        jMenu1.setText("Alugar");

        jMenuItem1.setText("Alugar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Devolução");

        jMenuItem2.setText("Devolução");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButtonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            String[] linha = new String[5]; // Array to hold data for each row
            Automovel aux = null; // Temporary variable to hold each Automovel object

            // Loop through the ArrayList of Automovel objects
            for (int i = 0; i < automoveis.size(); i++) {
                aux = automoveis.get(i); // Get the current Automovel object

                // Populate the row with data from the Automovel object
                linha[0] = String.valueOf(aux.getIdAutomovel()); // id
                linha[1] = aux.getModelo(); // modelo
                linha[2] = aux.getTipoVeic().getDescricao(); // tipo_veiculo (enum value as String)
                linha[3] = String.valueOf(aux.getValorDia()); // valor_dia (converted to String)
                linha[4] = aux.getStatus().getDescricao(); // status (enum value as String)

                // Add the row to the JTable model
                modelL.addRow(linha);
            }
        } catch (Exception ex) {
            Logger.getLogger(JFrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanel1.removeAll();
        jPanel1.add(jAlugar);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jPanel1.removeAll();
        jPanel1.add(jDevolucao);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jIDContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDContratoActionPerformed

    public boolean VerificarVazio(JPanel panel) {
        boolean vazio = false;

        for (Component component : panel.getComponents()) {
            if (component instanceof JTextField textField) {
                if (textField.getText().trim().isEmpty()) { // Check if the field is empty
                    vazio = true;
                    break; // Exit loop if an empty field is found
                }
            }
        }
        return vazio;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (VerificarVazio(jDevolucao)) {
            JOptionPane.showMessageDialog(this, "Há campos vazios", "Preencha e tente novamente", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "Prosseguir?", "", JOptionPane.YES_NO_OPTION);
        switch (confirm) {
            case JOptionPane.YES_OPTION -> {
                try {
                    if (!Locadora.Devolver(Integer.parseInt(jIDContrato.getText()))) {
                    } else {
                        JOptionPane.showMessageDialog(this, "Devolvido com sucesso", "", JOptionPane.OK_OPTION);
                        dispose();
                    }
                } catch (RemoteException ex) {
                    Logger.getLogger(JDialogLocacao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case JOptionPane.NO_OPTION ->
                System.out.println("...");
            default ->
                System.out.println("...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jConfirmAlugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmAlugaActionPerformed
        if (VerificarVazio(jAlugar)) {
            return;
        }
        userC = (Alugador) userC;
        userL = (Locador) userL;
        int idContrato = 0;
        try {
            idContrato = Locadora.ContratoAtual();
        } catch (RemoteException ex) {
            Logger.getLogger(JDialogLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        Automovel auto = null;

        Seguro seguro = new Seguro(jComboSeguro.getSelectedIndex() + 1);
        int a = 0;

        Object value = jTable1.getValueAt(jTable1.getSelectedRow(), 0);

        String valueAsString = value.toString();

        try {
            a = Integer.parseInt(valueAsString);
        } catch (NumberFormatException e) {
            System.err.println("The value in the table is not a valid integer: " + valueAsString);
        }

        auto = automoveis.get(a);

        try {
            Locadora.CriarContrato(idContrato, userC, userL, seguro, auto.getValorDia(), auto);
        } catch (RemoteException ex) {
            Logger.getLogger(JDialogLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jConfirmAlugaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        int idx = 0;
        try {
            System.out.println("Entrou no try busca");
            userC = (Alugador) Locadora.buscarUsuario(jTextBusca.getText());
            System.out.println("Index = " + idx);
            

        } catch (RemoteException ex) {
            Logger.getLogger(JDialogLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jToggleFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleFoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleFoundActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jAlugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboSeguro;
    private javax.swing.JButton jConfirmAluga;
    private javax.swing.JPanel jDevolucao;
    private javax.swing.JTextField jIDCliente;
    private javax.swing.JTextField jIDContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelVazio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextBusca;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleFound;
    // End of variables declaration//GEN-END:variables
}
